/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    EducationCreateDto,
    EducationCreateDtoFromJSON,
    EducationCreateDtoToJSON,
    EducationEntity,
    EducationEntityFromJSON,
    EducationEntityToJSON,
    EducationUpdateDto,
    EducationUpdateDtoFromJSON,
    EducationUpdateDtoToJSON,
} from '../models';

export interface CreateEducationRequest {
    educationCreateDto: EducationCreateDto;
}

export interface DeleteEducationRequest {
    id: string;
}

export interface FindOneEducationRequest {
    id: string;
}

export interface UpdateEducationRequest {
    id: string;
    educationUpdateDto: EducationUpdateDto;
}

/**
 * 
 */
export class EducationApi extends runtime.BaseAPI {

    /**
     */
    async createEducationRaw(requestParameters: CreateEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<EducationEntity>> {
        if (requestParameters.educationCreateDto === null || requestParameters.educationCreateDto === undefined) {
            throw new runtime.RequiredError('educationCreateDto','Required parameter requestParameters.educationCreateDto was null or undefined when calling createEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/educations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EducationCreateDtoToJSON(requestParameters.educationCreateDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EducationEntityFromJSON(jsonValue));
    }

    /**
     */
    async createEducation(requestParameters: CreateEducationRequest, initOverrides?: RequestInit): Promise<EducationEntity> {
        const response = await this.createEducationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteEducationRaw(requestParameters: DeleteEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<EducationEntity>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/educations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EducationEntityFromJSON(jsonValue));
    }

    /**
     */
    async deleteEducation(requestParameters: DeleteEducationRequest, initOverrides?: RequestInit): Promise<EducationEntity> {
        const response = await this.deleteEducationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async findManyEducationRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<EducationEntity>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/educations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(EducationEntityFromJSON));
    }

    /**
     */
    async findManyEducation(initOverrides?: RequestInit): Promise<Array<EducationEntity>> {
        const response = await this.findManyEducationRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async findOneEducationRaw(requestParameters: FindOneEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<EducationEntity>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/educations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EducationEntityFromJSON(jsonValue));
    }

    /**
     */
    async findOneEducation(requestParameters: FindOneEducationRequest, initOverrides?: RequestInit): Promise<EducationEntity> {
        const response = await this.findOneEducationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateEducationRaw(requestParameters: UpdateEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<EducationEntity>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateEducation.');
        }

        if (requestParameters.educationUpdateDto === null || requestParameters.educationUpdateDto === undefined) {
            throw new runtime.RequiredError('educationUpdateDto','Required parameter requestParameters.educationUpdateDto was null or undefined when calling updateEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/educations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EducationUpdateDtoToJSON(requestParameters.educationUpdateDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EducationEntityFromJSON(jsonValue));
    }

    /**
     */
    async updateEducation(requestParameters: UpdateEducationRequest, initOverrides?: RequestInit): Promise<EducationEntity> {
        const response = await this.updateEducationRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
