/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    AwardCreateDto,
    AwardCreateDtoFromJSON,
    AwardCreateDtoToJSON,
    AwardUpdateDto,
    AwardUpdateDtoFromJSON,
    AwardUpdateDtoToJSON,
    BasicCreateDto,
    BasicCreateDtoFromJSON,
    BasicCreateDtoToJSON,
    BasicUpdateDto,
    BasicUpdateDtoFromJSON,
    BasicUpdateDtoToJSON,
    EducationCreateDto,
    EducationCreateDtoFromJSON,
    EducationCreateDtoToJSON,
    EducationUpdateDto,
    EducationUpdateDtoFromJSON,
    EducationUpdateDtoToJSON,
    InterestCreateDto,
    InterestCreateDtoFromJSON,
    InterestCreateDtoToJSON,
    InterestUpdateDto,
    InterestUpdateDtoFromJSON,
    InterestUpdateDtoToJSON,
    LanguageCreateDto,
    LanguageCreateDtoFromJSON,
    LanguageCreateDtoToJSON,
    LanguageUpdateDto,
    LanguageUpdateDtoFromJSON,
    LanguageUpdateDtoToJSON,
    LocationCreateDto,
    LocationCreateDtoFromJSON,
    LocationCreateDtoToJSON,
    LocationUpdateDto,
    LocationUpdateDtoFromJSON,
    LocationUpdateDtoToJSON,
    ProfileCreateDto,
    ProfileCreateDtoFromJSON,
    ProfileCreateDtoToJSON,
    ProfileUpdateDto,
    ProfileUpdateDtoFromJSON,
    ProfileUpdateDtoToJSON,
    ProjectCreateDto,
    ProjectCreateDtoFromJSON,
    ProjectCreateDtoToJSON,
    ProjectUpdateDto,
    ProjectUpdateDtoFromJSON,
    ProjectUpdateDtoToJSON,
    PublicationCreateDto,
    PublicationCreateDtoFromJSON,
    PublicationCreateDtoToJSON,
    PublicationUpdateDto,
    PublicationUpdateDtoFromJSON,
    PublicationUpdateDtoToJSON,
    ReferenceCreateDto,
    ReferenceCreateDtoFromJSON,
    ReferenceCreateDtoToJSON,
    ReferenceUpdateDto,
    ReferenceUpdateDtoFromJSON,
    ReferenceUpdateDtoToJSON,
    SkillCreateDto,
    SkillCreateDtoFromJSON,
    SkillCreateDtoToJSON,
    SkillKeywordCreateDto,
    SkillKeywordCreateDtoFromJSON,
    SkillKeywordCreateDtoToJSON,
    SkillUpdateDto,
    SkillUpdateDtoFromJSON,
    SkillUpdateDtoToJSON,
    UserCreateDto,
    UserCreateDtoFromJSON,
    UserCreateDtoToJSON,
    VolunteerCreateDto,
    VolunteerCreateDtoFromJSON,
    VolunteerCreateDtoToJSON,
    VolunteerUpdateDto,
    VolunteerUpdateDtoFromJSON,
    VolunteerUpdateDtoToJSON,
    WorkCreateDto,
    WorkCreateDtoFromJSON,
    WorkCreateDtoToJSON,
    WorkUpdateDto,
    WorkUpdateDtoFromJSON,
    WorkUpdateDtoToJSON,
} from '../models';

export interface CreateAwardRequest {
    awardCreateDto: AwardCreateDto;
}

export interface CreateBasicRequest {
    basicCreateDto: BasicCreateDto;
}

export interface CreateEducationRequest {
    educationCreateDto: EducationCreateDto;
}

export interface CreateInterestRequest {
    interestCreateDto: InterestCreateDto;
}

export interface CreateLanguageRequest {
    languageCreateDto: LanguageCreateDto;
}

export interface CreateLocationRequest {
    locationCreateDto: LocationCreateDto;
}

export interface CreateProfileRequest {
    profileCreateDto: ProfileCreateDto;
}

export interface CreateProjectRequest {
    projectCreateDto: ProjectCreateDto;
}

export interface CreatePublicationRequest {
    publicationCreateDto: PublicationCreateDto;
}

export interface CreateReferenceRequest {
    referenceCreateDto: ReferenceCreateDto;
}

export interface CreateSkillRequest {
    skillCreateDto: SkillCreateDto;
}

export interface CreateSkillKeywordRequest {
    skillKeywordCreateDto: SkillKeywordCreateDto;
}

export interface CreateUserRequest {
    userCreateDto: UserCreateDto;
}

export interface CreateVolunteerRequest {
    volunteerCreateDto: VolunteerCreateDto;
}

export interface CreateWorkRequest {
    workCreateDto: WorkCreateDto;
}

export interface DeleteAwardRequest {
    id: string;
}

export interface DeleteBasicRequest {
    id: string;
}

export interface DeleteEducationRequest {
    id: string;
}

export interface DeleteInterestRequest {
    id: string;
}

export interface DeleteLanguageRequest {
    id: string;
}

export interface DeleteLocationRequest {
    id: string;
}

export interface DeleteProfileRequest {
    id: string;
}

export interface DeleteProjectRequest {
    id: string;
}

export interface DeletePublicationRequest {
    id: string;
}

export interface DeleteReferenceRequest {
    id: string;
}

export interface DeleteSkillRequest {
    id: string;
}

export interface DeleteSkillKeywordRequest {
    id: string;
}

export interface DeleteUserRequest {
    id: string;
}

export interface DeleteVolunteerRequest {
    id: string;
}

export interface DeleteWorkRequest {
    id: string;
}

export interface FindOneAwardRequest {
    id: string;
}

export interface FindOneBasicRequest {
    id: string;
}

export interface FindOneEducationRequest {
    id: string;
}

export interface FindOneInterestRequest {
    id: string;
}

export interface FindOneLanguageRequest {
    id: string;
}

export interface FindOneLocationRequest {
    id: string;
}

export interface FindOneProfileRequest {
    id: string;
}

export interface FindOneProjectRequest {
    id: string;
}

export interface FindOnePublicationRequest {
    id: string;
}

export interface FindOneReferenceRequest {
    id: string;
}

export interface FindOneSkillRequest {
    id: string;
}

export interface FindOneSkillKeywordRequest {
    id: string;
}

export interface FindOneUserRequest {
    id: string;
}

export interface FindOneVolunteerRequest {
    id: string;
}

export interface FindOneWorkRequest {
    id: string;
}

export interface UpdateAwardRequest {
    id: string;
    awardUpdateDto: AwardUpdateDto;
}

export interface UpdateBasicRequest {
    id: string;
    basicUpdateDto: BasicUpdateDto;
}

export interface UpdateEducationRequest {
    id: string;
    educationUpdateDto: EducationUpdateDto;
}

export interface UpdateInterestRequest {
    id: string;
    interestUpdateDto: InterestUpdateDto;
}

export interface UpdateLanguageRequest {
    id: string;
    languageUpdateDto: LanguageUpdateDto;
}

export interface UpdateLocationRequest {
    id: string;
    locationUpdateDto: LocationUpdateDto;
}

export interface UpdateProfileRequest {
    id: string;
    profileUpdateDto: ProfileUpdateDto;
}

export interface UpdateProjectRequest {
    id: string;
    projectUpdateDto: ProjectUpdateDto;
}

export interface UpdatePublicationRequest {
    id: string;
    publicationUpdateDto: PublicationUpdateDto;
}

export interface UpdateReferenceRequest {
    id: string;
    referenceUpdateDto: ReferenceUpdateDto;
}

export interface UpdateSkillRequest {
    id: string;
    skillUpdateDto: SkillUpdateDto;
}

export interface UpdateSkillKeywordRequest {
    id: string;
    body: object;
}

export interface UpdateUserRequest {
    id: string;
    body: object;
}

export interface UpdateVolunteerRequest {
    id: string;
    volunteerUpdateDto: VolunteerUpdateDto;
}

export interface UpdateWorkRequest {
    id: string;
    workUpdateDto: WorkUpdateDto;
}

/**
 * 
 */
export class PrismaApi extends runtime.BaseAPI {

    /**
     */
    async createAwardRaw(requestParameters: CreateAwardRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.awardCreateDto === null || requestParameters.awardCreateDto === undefined) {
            throw new runtime.RequiredError('awardCreateDto','Required parameter requestParameters.awardCreateDto was null or undefined when calling createAward.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/awards`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AwardCreateDtoToJSON(requestParameters.awardCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createAward(requestParameters: CreateAwardRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createAwardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createBasicRaw(requestParameters: CreateBasicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.basicCreateDto === null || requestParameters.basicCreateDto === undefined) {
            throw new runtime.RequiredError('basicCreateDto','Required parameter requestParameters.basicCreateDto was null or undefined when calling createBasic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/basics`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BasicCreateDtoToJSON(requestParameters.basicCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createBasic(requestParameters: CreateBasicRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createBasicRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createEducationRaw(requestParameters: CreateEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.educationCreateDto === null || requestParameters.educationCreateDto === undefined) {
            throw new runtime.RequiredError('educationCreateDto','Required parameter requestParameters.educationCreateDto was null or undefined when calling createEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/educations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EducationCreateDtoToJSON(requestParameters.educationCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createEducation(requestParameters: CreateEducationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createEducationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createInterestRaw(requestParameters: CreateInterestRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.interestCreateDto === null || requestParameters.interestCreateDto === undefined) {
            throw new runtime.RequiredError('interestCreateDto','Required parameter requestParameters.interestCreateDto was null or undefined when calling createInterest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/interests`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InterestCreateDtoToJSON(requestParameters.interestCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createInterest(requestParameters: CreateInterestRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createInterestRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createLanguageRaw(requestParameters: CreateLanguageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.languageCreateDto === null || requestParameters.languageCreateDto === undefined) {
            throw new runtime.RequiredError('languageCreateDto','Required parameter requestParameters.languageCreateDto was null or undefined when calling createLanguage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/languages`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LanguageCreateDtoToJSON(requestParameters.languageCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createLanguage(requestParameters: CreateLanguageRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createLanguageRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createLocationRaw(requestParameters: CreateLocationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.locationCreateDto === null || requestParameters.locationCreateDto === undefined) {
            throw new runtime.RequiredError('locationCreateDto','Required parameter requestParameters.locationCreateDto was null or undefined when calling createLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/locations`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: LocationCreateDtoToJSON(requestParameters.locationCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createLocation(requestParameters: CreateLocationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createLocationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createProfileRaw(requestParameters: CreateProfileRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.profileCreateDto === null || requestParameters.profileCreateDto === undefined) {
            throw new runtime.RequiredError('profileCreateDto','Required parameter requestParameters.profileCreateDto was null or undefined when calling createProfile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/profiles`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileCreateDtoToJSON(requestParameters.profileCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createProfile(requestParameters: CreateProfileRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createProfileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createProjectRaw(requestParameters: CreateProjectRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.projectCreateDto === null || requestParameters.projectCreateDto === undefined) {
            throw new runtime.RequiredError('projectCreateDto','Required parameter requestParameters.projectCreateDto was null or undefined when calling createProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectCreateDtoToJSON(requestParameters.projectCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createProject(requestParameters: CreateProjectRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createProjectRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createPublicationRaw(requestParameters: CreatePublicationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.publicationCreateDto === null || requestParameters.publicationCreateDto === undefined) {
            throw new runtime.RequiredError('publicationCreateDto','Required parameter requestParameters.publicationCreateDto was null or undefined when calling createPublication.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/publications`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PublicationCreateDtoToJSON(requestParameters.publicationCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createPublication(requestParameters: CreatePublicationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createPublicationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createReferenceRaw(requestParameters: CreateReferenceRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.referenceCreateDto === null || requestParameters.referenceCreateDto === undefined) {
            throw new runtime.RequiredError('referenceCreateDto','Required parameter requestParameters.referenceCreateDto was null or undefined when calling createReference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/references`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReferenceCreateDtoToJSON(requestParameters.referenceCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createReference(requestParameters: CreateReferenceRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createReferenceRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createSkillRaw(requestParameters: CreateSkillRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.skillCreateDto === null || requestParameters.skillCreateDto === undefined) {
            throw new runtime.RequiredError('skillCreateDto','Required parameter requestParameters.skillCreateDto was null or undefined when calling createSkill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/skills`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SkillCreateDtoToJSON(requestParameters.skillCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createSkill(requestParameters: CreateSkillRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createSkillRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createSkillKeywordRaw(requestParameters: CreateSkillKeywordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.skillKeywordCreateDto === null || requestParameters.skillKeywordCreateDto === undefined) {
            throw new runtime.RequiredError('skillKeywordCreateDto','Required parameter requestParameters.skillKeywordCreateDto was null or undefined when calling createSkillKeyword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/skillKeywords`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SkillKeywordCreateDtoToJSON(requestParameters.skillKeywordCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createSkillKeyword(requestParameters: CreateSkillKeywordRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createSkillKeywordRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createUserRaw(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.userCreateDto === null || requestParameters.userCreateDto === undefined) {
            throw new runtime.RequiredError('userCreateDto','Required parameter requestParameters.userCreateDto was null or undefined when calling createUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserCreateDtoToJSON(requestParameters.userCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createUser(requestParameters: CreateUserRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createVolunteerRaw(requestParameters: CreateVolunteerRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.volunteerCreateDto === null || requestParameters.volunteerCreateDto === undefined) {
            throw new runtime.RequiredError('volunteerCreateDto','Required parameter requestParameters.volunteerCreateDto was null or undefined when calling createVolunteer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/volunteers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VolunteerCreateDtoToJSON(requestParameters.volunteerCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createVolunteer(requestParameters: CreateVolunteerRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createVolunteerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async createWorkRaw(requestParameters: CreateWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.workCreateDto === null || requestParameters.workCreateDto === undefined) {
            throw new runtime.RequiredError('workCreateDto','Required parameter requestParameters.workCreateDto was null or undefined when calling createWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/works`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkCreateDtoToJSON(requestParameters.workCreateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async createWork(requestParameters: CreateWorkRequest, initOverrides?: RequestInit): Promise<void> {
        await this.createWorkRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteAwardRaw(requestParameters: DeleteAwardRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteAward.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/awards/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteAward(requestParameters: DeleteAwardRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteAwardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteBasicRaw(requestParameters: DeleteBasicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteBasic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/basics/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteBasic(requestParameters: DeleteBasicRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteBasicRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteEducationRaw(requestParameters: DeleteEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/educations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteEducation(requestParameters: DeleteEducationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteEducationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteInterestRaw(requestParameters: DeleteInterestRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteInterest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/interests/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteInterest(requestParameters: DeleteInterestRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteInterestRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteLanguageRaw(requestParameters: DeleteLanguageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteLanguage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/languages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteLanguage(requestParameters: DeleteLanguageRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteLanguageRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteLocationRaw(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteLocation(requestParameters: DeleteLocationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteLocationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteProfileRaw(requestParameters: DeleteProfileRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteProfile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profiles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteProfile(requestParameters: DeleteProfileRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteProfileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteProjectRaw(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteProject(requestParameters: DeleteProjectRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteProjectRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deletePublicationRaw(requestParameters: DeletePublicationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deletePublication.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/publications/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deletePublication(requestParameters: DeletePublicationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deletePublicationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteReferenceRaw(requestParameters: DeleteReferenceRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteReference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/references/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteReference(requestParameters: DeleteReferenceRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteReferenceRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteSkillRaw(requestParameters: DeleteSkillRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteSkill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/skills/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteSkill(requestParameters: DeleteSkillRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteSkillRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteSkillKeywordRaw(requestParameters: DeleteSkillKeywordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteSkillKeyword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/skillKeywords/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteSkillKeyword(requestParameters: DeleteSkillKeywordRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteSkillKeywordRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteUserRaw(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteUser(requestParameters: DeleteUserRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteVolunteerRaw(requestParameters: DeleteVolunteerRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteVolunteer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volunteers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteVolunteer(requestParameters: DeleteVolunteerRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteVolunteerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async deleteWorkRaw(requestParameters: DeleteWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/works/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async deleteWork(requestParameters: DeleteWorkRequest, initOverrides?: RequestInit): Promise<void> {
        await this.deleteWorkRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findManyAwardRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/awards`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyAward(initOverrides?: RequestInit): Promise<void> {
        await this.findManyAwardRaw(initOverrides);
    }

    /**
     */
    async findManyBasicRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/basics`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyBasic(initOverrides?: RequestInit): Promise<void> {
        await this.findManyBasicRaw(initOverrides);
    }

    /**
     */
    async findManyEducationRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/educations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyEducation(initOverrides?: RequestInit): Promise<void> {
        await this.findManyEducationRaw(initOverrides);
    }

    /**
     */
    async findManyInterestRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/interests`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyInterest(initOverrides?: RequestInit): Promise<void> {
        await this.findManyInterestRaw(initOverrides);
    }

    /**
     */
    async findManyLanguageRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/languages`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyLanguage(initOverrides?: RequestInit): Promise<void> {
        await this.findManyLanguageRaw(initOverrides);
    }

    /**
     */
    async findManyLocationRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyLocation(initOverrides?: RequestInit): Promise<void> {
        await this.findManyLocationRaw(initOverrides);
    }

    /**
     */
    async findManyProfileRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyProfile(initOverrides?: RequestInit): Promise<void> {
        await this.findManyProfileRaw(initOverrides);
    }

    /**
     */
    async findManyProjectRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyProject(initOverrides?: RequestInit): Promise<void> {
        await this.findManyProjectRaw(initOverrides);
    }

    /**
     */
    async findManyPublicationRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/publications`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyPublication(initOverrides?: RequestInit): Promise<void> {
        await this.findManyPublicationRaw(initOverrides);
    }

    /**
     */
    async findManyReferenceRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/references`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyReference(initOverrides?: RequestInit): Promise<void> {
        await this.findManyReferenceRaw(initOverrides);
    }

    /**
     */
    async findManySkillRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/skills`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManySkill(initOverrides?: RequestInit): Promise<void> {
        await this.findManySkillRaw(initOverrides);
    }

    /**
     */
    async findManySkillKeywordRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/skillKeywords`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManySkillKeyword(initOverrides?: RequestInit): Promise<void> {
        await this.findManySkillKeywordRaw(initOverrides);
    }

    /**
     */
    async findManyUserRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyUser(initOverrides?: RequestInit): Promise<void> {
        await this.findManyUserRaw(initOverrides);
    }

    /**
     */
    async findManyVolunteerRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volunteers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyVolunteer(initOverrides?: RequestInit): Promise<void> {
        await this.findManyVolunteerRaw(initOverrides);
    }

    /**
     */
    async findManyWorkRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/works`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findManyWork(initOverrides?: RequestInit): Promise<void> {
        await this.findManyWorkRaw(initOverrides);
    }

    /**
     */
    async findOneAwardRaw(requestParameters: FindOneAwardRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneAward.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/awards/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneAward(requestParameters: FindOneAwardRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneAwardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneBasicRaw(requestParameters: FindOneBasicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneBasic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/basics/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneBasic(requestParameters: FindOneBasicRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneBasicRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneEducationRaw(requestParameters: FindOneEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/educations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneEducation(requestParameters: FindOneEducationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneEducationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneInterestRaw(requestParameters: FindOneInterestRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneInterest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/interests/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneInterest(requestParameters: FindOneInterestRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneInterestRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneLanguageRaw(requestParameters: FindOneLanguageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneLanguage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/languages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneLanguage(requestParameters: FindOneLanguageRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneLanguageRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneLocationRaw(requestParameters: FindOneLocationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/locations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneLocation(requestParameters: FindOneLocationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneLocationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneProfileRaw(requestParameters: FindOneProfileRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneProfile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/profiles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneProfile(requestParameters: FindOneProfileRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneProfileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneProjectRaw(requestParameters: FindOneProjectRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/projects/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneProject(requestParameters: FindOneProjectRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneProjectRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOnePublicationRaw(requestParameters: FindOnePublicationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOnePublication.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/publications/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOnePublication(requestParameters: FindOnePublicationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOnePublicationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneReferenceRaw(requestParameters: FindOneReferenceRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneReference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/references/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneReference(requestParameters: FindOneReferenceRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneReferenceRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneSkillRaw(requestParameters: FindOneSkillRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneSkill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/skills/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneSkill(requestParameters: FindOneSkillRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneSkillRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneSkillKeywordRaw(requestParameters: FindOneSkillKeywordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneSkillKeyword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/skillKeywords/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneSkillKeyword(requestParameters: FindOneSkillKeywordRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneSkillKeywordRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneUserRaw(requestParameters: FindOneUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneUser(requestParameters: FindOneUserRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneVolunteerRaw(requestParameters: FindOneVolunteerRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneVolunteer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/volunteers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneVolunteer(requestParameters: FindOneVolunteerRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneVolunteerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async findOneWorkRaw(requestParameters: FindOneWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/works/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async findOneWork(requestParameters: FindOneWorkRequest, initOverrides?: RequestInit): Promise<void> {
        await this.findOneWorkRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateAwardRaw(requestParameters: UpdateAwardRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateAward.');
        }

        if (requestParameters.awardUpdateDto === null || requestParameters.awardUpdateDto === undefined) {
            throw new runtime.RequiredError('awardUpdateDto','Required parameter requestParameters.awardUpdateDto was null or undefined when calling updateAward.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/awards/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AwardUpdateDtoToJSON(requestParameters.awardUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateAward(requestParameters: UpdateAwardRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateAwardRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateBasicRaw(requestParameters: UpdateBasicRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateBasic.');
        }

        if (requestParameters.basicUpdateDto === null || requestParameters.basicUpdateDto === undefined) {
            throw new runtime.RequiredError('basicUpdateDto','Required parameter requestParameters.basicUpdateDto was null or undefined when calling updateBasic.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/basics/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: BasicUpdateDtoToJSON(requestParameters.basicUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateBasic(requestParameters: UpdateBasicRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateBasicRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateEducationRaw(requestParameters: UpdateEducationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateEducation.');
        }

        if (requestParameters.educationUpdateDto === null || requestParameters.educationUpdateDto === undefined) {
            throw new runtime.RequiredError('educationUpdateDto','Required parameter requestParameters.educationUpdateDto was null or undefined when calling updateEducation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/educations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: EducationUpdateDtoToJSON(requestParameters.educationUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateEducation(requestParameters: UpdateEducationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateEducationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateInterestRaw(requestParameters: UpdateInterestRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateInterest.');
        }

        if (requestParameters.interestUpdateDto === null || requestParameters.interestUpdateDto === undefined) {
            throw new runtime.RequiredError('interestUpdateDto','Required parameter requestParameters.interestUpdateDto was null or undefined when calling updateInterest.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/interests/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: InterestUpdateDtoToJSON(requestParameters.interestUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateInterest(requestParameters: UpdateInterestRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateInterestRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateLanguageRaw(requestParameters: UpdateLanguageRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateLanguage.');
        }

        if (requestParameters.languageUpdateDto === null || requestParameters.languageUpdateDto === undefined) {
            throw new runtime.RequiredError('languageUpdateDto','Required parameter requestParameters.languageUpdateDto was null or undefined when calling updateLanguage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/languages/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: LanguageUpdateDtoToJSON(requestParameters.languageUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateLanguage(requestParameters: UpdateLanguageRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateLanguageRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateLocationRaw(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateLocation.');
        }

        if (requestParameters.locationUpdateDto === null || requestParameters.locationUpdateDto === undefined) {
            throw new runtime.RequiredError('locationUpdateDto','Required parameter requestParameters.locationUpdateDto was null or undefined when calling updateLocation.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/locations/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: LocationUpdateDtoToJSON(requestParameters.locationUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateLocation(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateLocationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateProfileRaw(requestParameters: UpdateProfileRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateProfile.');
        }

        if (requestParameters.profileUpdateDto === null || requestParameters.profileUpdateDto === undefined) {
            throw new runtime.RequiredError('profileUpdateDto','Required parameter requestParameters.profileUpdateDto was null or undefined when calling updateProfile.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/profiles/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProfileUpdateDtoToJSON(requestParameters.profileUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateProfile(requestParameters: UpdateProfileRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateProfileRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateProjectRaw(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateProject.');
        }

        if (requestParameters.projectUpdateDto === null || requestParameters.projectUpdateDto === undefined) {
            throw new runtime.RequiredError('projectUpdateDto','Required parameter requestParameters.projectUpdateDto was null or undefined when calling updateProject.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/projects/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectUpdateDtoToJSON(requestParameters.projectUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateProject(requestParameters: UpdateProjectRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateProjectRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updatePublicationRaw(requestParameters: UpdatePublicationRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updatePublication.');
        }

        if (requestParameters.publicationUpdateDto === null || requestParameters.publicationUpdateDto === undefined) {
            throw new runtime.RequiredError('publicationUpdateDto','Required parameter requestParameters.publicationUpdateDto was null or undefined when calling updatePublication.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/publications/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PublicationUpdateDtoToJSON(requestParameters.publicationUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updatePublication(requestParameters: UpdatePublicationRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updatePublicationRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateReferenceRaw(requestParameters: UpdateReferenceRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateReference.');
        }

        if (requestParameters.referenceUpdateDto === null || requestParameters.referenceUpdateDto === undefined) {
            throw new runtime.RequiredError('referenceUpdateDto','Required parameter requestParameters.referenceUpdateDto was null or undefined when calling updateReference.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/references/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ReferenceUpdateDtoToJSON(requestParameters.referenceUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateReference(requestParameters: UpdateReferenceRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateReferenceRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateSkillRaw(requestParameters: UpdateSkillRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateSkill.');
        }

        if (requestParameters.skillUpdateDto === null || requestParameters.skillUpdateDto === undefined) {
            throw new runtime.RequiredError('skillUpdateDto','Required parameter requestParameters.skillUpdateDto was null or undefined when calling updateSkill.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/skills/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SkillUpdateDtoToJSON(requestParameters.skillUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateSkill(requestParameters: UpdateSkillRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateSkillRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateSkillKeywordRaw(requestParameters: UpdateSkillKeywordRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateSkillKeyword.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling updateSkillKeyword.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/skillKeywords/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateSkillKeyword(requestParameters: UpdateSkillKeywordRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateSkillKeywordRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateUserRaw(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateUser.');
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError('body','Required parameter requestParameters.body was null or undefined when calling updateUser.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.body as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateUser(requestParameters: UpdateUserRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateUserRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateVolunteerRaw(requestParameters: UpdateVolunteerRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateVolunteer.');
        }

        if (requestParameters.volunteerUpdateDto === null || requestParameters.volunteerUpdateDto === undefined) {
            throw new runtime.RequiredError('volunteerUpdateDto','Required parameter requestParameters.volunteerUpdateDto was null or undefined when calling updateVolunteer.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/volunteers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: VolunteerUpdateDtoToJSON(requestParameters.volunteerUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateVolunteer(requestParameters: UpdateVolunteerRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateVolunteerRaw(requestParameters, initOverrides);
    }

    /**
     */
    async updateWorkRaw(requestParameters: UpdateWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateWork.');
        }

        if (requestParameters.workUpdateDto === null || requestParameters.workUpdateDto === undefined) {
            throw new runtime.RequiredError('workUpdateDto','Required parameter requestParameters.workUpdateDto was null or undefined when calling updateWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/works/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WorkUpdateDtoToJSON(requestParameters.workUpdateDto),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async updateWork(requestParameters: UpdateWorkRequest, initOverrides?: RequestInit): Promise<void> {
        await this.updateWorkRaw(requestParameters, initOverrides);
    }

}
