/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    WorkCreateDto,
    WorkCreateDtoFromJSON,
    WorkCreateDtoToJSON,
    WorkEntity,
    WorkEntityFromJSON,
    WorkEntityToJSON,
    WorkUpdateDto,
    WorkUpdateDtoFromJSON,
    WorkUpdateDtoToJSON,
} from '../models';

export interface CreateWorkRequest {
    workCreateDto: WorkCreateDto;
}

export interface DeleteWorkRequest {
    id: string;
}

export interface FindOneWorkRequest {
    id: string;
}

export interface UpdateWorkRequest {
    id: string;
    workUpdateDto: WorkUpdateDto;
}

/**
 * 
 */
export class WorkApi extends runtime.BaseAPI {

    /**
     */
    async createWorkRaw(requestParameters: CreateWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WorkEntity>> {
        if (requestParameters.workCreateDto === null || requestParameters.workCreateDto === undefined) {
            throw new runtime.RequiredError('workCreateDto','Required parameter requestParameters.workCreateDto was null or undefined when calling createWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/works`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WorkCreateDtoToJSON(requestParameters.workCreateDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkEntityFromJSON(jsonValue));
    }

    /**
     */
    async createWork(requestParameters: CreateWorkRequest, initOverrides?: RequestInit): Promise<WorkEntity> {
        const response = await this.createWorkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async deleteWorkRaw(requestParameters: DeleteWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WorkEntity>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/works/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkEntityFromJSON(jsonValue));
    }

    /**
     */
    async deleteWork(requestParameters: DeleteWorkRequest, initOverrides?: RequestInit): Promise<WorkEntity> {
        const response = await this.deleteWorkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async findManyWorkRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<WorkEntity>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/works`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(WorkEntityFromJSON));
    }

    /**
     */
    async findManyWork(initOverrides?: RequestInit): Promise<Array<WorkEntity>> {
        const response = await this.findManyWorkRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async findOneWorkRaw(requestParameters: FindOneWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WorkEntity>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling findOneWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/works/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkEntityFromJSON(jsonValue));
    }

    /**
     */
    async findOneWork(requestParameters: FindOneWorkRequest, initOverrides?: RequestInit): Promise<WorkEntity> {
        const response = await this.findOneWorkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateWorkRaw(requestParameters: UpdateWorkRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<WorkEntity>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling updateWork.');
        }

        if (requestParameters.workUpdateDto === null || requestParameters.workUpdateDto === undefined) {
            throw new runtime.RequiredError('workUpdateDto','Required parameter requestParameters.workUpdateDto was null or undefined when calling updateWork.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/works/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: WorkUpdateDtoToJSON(requestParameters.workUpdateDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WorkEntityFromJSON(jsonValue));
    }

    /**
     */
    async updateWork(requestParameters: UpdateWorkRequest, initOverrides?: RequestInit): Promise<WorkEntity> {
        const response = await this.updateWorkRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
