/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface AwardEntity
 */
export interface AwardEntity {
    /**
     * 
     * @type {number}
     * @memberof AwardEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AwardEntity
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof AwardEntity
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof AwardEntity
     */
    awarder: string;
    /**
     * 
     * @type {string}
     * @memberof AwardEntity
     */
    summary: string;
    /**
     * 
     * @type {number}
     * @memberof AwardEntity
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof AwardEntity
     */
    user?: User | null;
}

export function AwardEntityFromJSON(json: any): AwardEntity {
    return AwardEntityFromJSONTyped(json, false);
}

export function AwardEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): AwardEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
        'date': (new Date(json['date'])),
        'awarder': json['awarder'],
        'summary': json['summary'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function AwardEntityToJSON(value?: AwardEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'date': (value.date.toISOString()),
        'awarder': value.awarder,
        'summary': value.summary,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

