/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateBasicUserRelationInputDto,
    CreateBasicUserRelationInputDtoFromJSON,
    CreateBasicUserRelationInputDtoFromJSONTyped,
    CreateBasicUserRelationInputDtoToJSON,
} from './CreateBasicUserRelationInputDto';

/**
 * 
 * @export
 * @interface BasicCreateDto
 */
export interface BasicCreateDto {
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    label: string;
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof BasicCreateDto
     */
    summary: string;
    /**
     * 
     * @type {CreateBasicUserRelationInputDto}
     * @memberof BasicCreateDto
     */
    user?: CreateBasicUserRelationInputDto;
}

export function BasicCreateDtoFromJSON(json: any): BasicCreateDto {
    return BasicCreateDtoFromJSONTyped(json, false);
}

export function BasicCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'lastName': json['lastName'],
        'email': json['email'],
        'label': json['label'],
        'image': json['image'],
        'phone': json['phone'],
        'summary': json['summary'],
        'user': !exists(json, 'user') ? undefined : CreateBasicUserRelationInputDtoFromJSON(json['user']),
    };
}

export function BasicCreateDtoToJSON(value?: BasicCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'label': value.label,
        'image': value.image,
        'phone': value.phone,
        'summary': value.summary,
        'user': CreateBasicUserRelationInputDtoToJSON(value.user),
    };
}

