/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BasicsUpdateDto
 */
export interface BasicsUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof BasicsUpdateDto
     */
    summary?: string;
}

export function BasicsUpdateDtoFromJSON(json: any): BasicsUpdateDto {
    return BasicsUpdateDtoFromJSONTyped(json, false);
}

export function BasicsUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BasicsUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': !exists(json, 'firstName') ? undefined : json['firstName'],
        'lastName': !exists(json, 'lastName') ? undefined : json['lastName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'phone': !exists(json, 'phone') ? undefined : json['phone'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
    };
}

export function BasicsUpdateDtoToJSON(value?: BasicsUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'firstName': value.firstName,
        'lastName': value.lastName,
        'email': value.email,
        'label': value.label,
        'image': value.image,
        'phone': value.phone,
        'summary': value.summary,
    };
}

