/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateLanguageDto,
    CreateLanguageDtoFromJSON,
    CreateLanguageDtoFromJSONTyped,
    CreateLanguageDtoToJSON,
} from './CreateLanguageDto';

/**
 * 
 * @export
 * @interface CreateUserLanguagesRelationInputDto
 */
export interface CreateUserLanguagesRelationInputDto {
    /**
     * 
     * @type {Array<CreateLanguageDto>}
     * @memberof CreateUserLanguagesRelationInputDto
     */
    create: Array<CreateLanguageDto>;
}

export function CreateUserLanguagesRelationInputDtoFromJSON(json: any): CreateUserLanguagesRelationInputDto {
    return CreateUserLanguagesRelationInputDtoFromJSONTyped(json, false);
}

export function CreateUserLanguagesRelationInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserLanguagesRelationInputDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'create': ((json['create'] as Array<any>).map(CreateLanguageDtoFromJSON)),
    };
}

export function CreateUserLanguagesRelationInputDtoToJSON(value?: CreateUserLanguagesRelationInputDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create': ((value.create as Array<any>).map(CreateLanguageDtoToJSON)),
    };
}

