/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateInterestDto,
    CreateInterestDtoFromJSON,
    CreateInterestDtoFromJSONTyped,
    CreateInterestDtoToJSON,
} from './CreateInterestDto';

/**
 * 
 * @export
 * @interface CreateUserInterestsRelationInputDto
 */
export interface CreateUserInterestsRelationInputDto {
    /**
     * 
     * @type {Array<CreateInterestDto>}
     * @memberof CreateUserInterestsRelationInputDto
     */
    create: Array<CreateInterestDto>;
}

export function CreateUserInterestsRelationInputDtoFromJSON(json: any): CreateUserInterestsRelationInputDto {
    return CreateUserInterestsRelationInputDtoFromJSONTyped(json, false);
}

export function CreateUserInterestsRelationInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserInterestsRelationInputDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'create': ((json['create'] as Array<any>).map(CreateInterestDtoFromJSON)),
    };
}

export function CreateUserInterestsRelationInputDtoToJSON(value?: CreateUserInterestsRelationInputDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create': ((value.create as Array<any>).map(CreateInterestDtoToJSON)),
    };
}

