/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateAwardDto,
    CreateAwardDtoFromJSON,
    CreateAwardDtoFromJSONTyped,
    CreateAwardDtoToJSON,
} from './CreateAwardDto';

/**
 * 
 * @export
 * @interface CreateUserAwardsRelationInputDto
 */
export interface CreateUserAwardsRelationInputDto {
    /**
     * 
     * @type {Array<CreateAwardDto>}
     * @memberof CreateUserAwardsRelationInputDto
     */
    create: Array<CreateAwardDto>;
}

export function CreateUserAwardsRelationInputDtoFromJSON(json: any): CreateUserAwardsRelationInputDto {
    return CreateUserAwardsRelationInputDtoFromJSONTyped(json, false);
}

export function CreateUserAwardsRelationInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserAwardsRelationInputDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'create': ((json['create'] as Array<any>).map(CreateAwardDtoFromJSON)),
    };
}

export function CreateUserAwardsRelationInputDtoToJSON(value?: CreateUserAwardsRelationInputDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create': ((value.create as Array<any>).map(CreateAwardDtoToJSON)),
    };
}

