/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatePublicationUserRelationInputDto,
    CreatePublicationUserRelationInputDtoFromJSON,
    CreatePublicationUserRelationInputDtoFromJSONTyped,
    CreatePublicationUserRelationInputDtoToJSON,
} from './CreatePublicationUserRelationInputDto';

/**
 * 
 * @export
 * @interface CreatePublicationDto
 */
export interface CreatePublicationDto {
    /**
     * 
     * @type {string}
     * @memberof CreatePublicationDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicationDto
     */
    publisher: string;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicationDto
     */
    url: string;
    /**
     * 
     * @type {Date}
     * @memberof CreatePublicationDto
     */
    releaseDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CreatePublicationDto
     */
    summary: string;
    /**
     * 
     * @type {CreatePublicationUserRelationInputDto}
     * @memberof CreatePublicationDto
     */
    user?: CreatePublicationUserRelationInputDto;
}

export function CreatePublicationDtoFromJSON(json: any): CreatePublicationDto {
    return CreatePublicationDtoFromJSONTyped(json, false);
}

export function CreatePublicationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePublicationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'publisher': json['publisher'],
        'url': json['url'],
        'releaseDate': (new Date(json['releaseDate'])),
        'summary': json['summary'],
        'user': !exists(json, 'user') ? undefined : CreatePublicationUserRelationInputDtoFromJSON(json['user']),
    };
}

export function CreatePublicationDtoToJSON(value?: CreatePublicationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'publisher': value.publisher,
        'url': value.url,
        'releaseDate': (value.releaseDate.toISOString()),
        'summary': value.summary,
        'user': CreatePublicationUserRelationInputDtoToJSON(value.user),
    };
}

