/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateEducationUserRelationInputDto,
    CreateEducationUserRelationInputDtoFromJSON,
    CreateEducationUserRelationInputDtoFromJSONTyped,
    CreateEducationUserRelationInputDtoToJSON,
} from './CreateEducationUserRelationInputDto';

/**
 * 
 * @export
 * @interface CreateEducationDto
 */
export interface CreateEducationDto {
    /**
     * 
     * @type {string}
     * @memberof CreateEducationDto
     */
    institution: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEducationDto
     */
    area: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEducationDto
     */
    studyType: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEducationDto
     */
    url: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateEducationDto
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateEducationDto
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateEducationDto
     */
    score: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateEducationDto
     */
    courses: Array<string>;
    /**
     * 
     * @type {CreateEducationUserRelationInputDto}
     * @memberof CreateEducationDto
     */
    user?: CreateEducationUserRelationInputDto;
}

export function CreateEducationDtoFromJSON(json: any): CreateEducationDto {
    return CreateEducationDtoFromJSONTyped(json, false);
}

export function CreateEducationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEducationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'institution': json['institution'],
        'area': json['area'],
        'studyType': json['studyType'],
        'url': json['url'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'score': json['score'],
        'courses': json['courses'],
        'user': !exists(json, 'user') ? undefined : CreateEducationUserRelationInputDtoFromJSON(json['user']),
    };
}

export function CreateEducationDtoToJSON(value?: CreateEducationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'institution': value.institution,
        'area': value.area,
        'studyType': value.studyType,
        'url': value.url,
        'startDate': (value.startDate.toISOString()),
        'endDate': (value.endDate.toISOString()),
        'score': value.score,
        'courses': value.courses,
        'user': CreateEducationUserRelationInputDtoToJSON(value.user),
    };
}

