/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreatePublicationDto,
    CreatePublicationDtoFromJSON,
    CreatePublicationDtoFromJSONTyped,
    CreatePublicationDtoToJSON,
} from './CreatePublicationDto';

/**
 * 
 * @export
 * @interface CreateUserPublicationsRelationInputDto
 */
export interface CreateUserPublicationsRelationInputDto {
    /**
     * 
     * @type {Array<CreatePublicationDto>}
     * @memberof CreateUserPublicationsRelationInputDto
     */
    create: Array<CreatePublicationDto>;
}

export function CreateUserPublicationsRelationInputDtoFromJSON(json: any): CreateUserPublicationsRelationInputDto {
    return CreateUserPublicationsRelationInputDtoFromJSONTyped(json, false);
}

export function CreateUserPublicationsRelationInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserPublicationsRelationInputDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'create': ((json['create'] as Array<any>).map(CreatePublicationDtoFromJSON)),
    };
}

export function CreateUserPublicationsRelationInputDtoToJSON(value?: CreateUserPublicationsRelationInputDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create': ((value.create as Array<any>).map(CreatePublicationDtoToJSON)),
    };
}

