/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateEducationDto,
    CreateEducationDtoFromJSON,
    CreateEducationDtoFromJSONTyped,
    CreateEducationDtoToJSON,
} from './CreateEducationDto';

/**
 * 
 * @export
 * @interface CreateUserEducationRelationInputDto
 */
export interface CreateUserEducationRelationInputDto {
    /**
     * 
     * @type {Array<CreateEducationDto>}
     * @memberof CreateUserEducationRelationInputDto
     */
    create: Array<CreateEducationDto>;
}

export function CreateUserEducationRelationInputDtoFromJSON(json: any): CreateUserEducationRelationInputDto {
    return CreateUserEducationRelationInputDtoFromJSONTyped(json, false);
}

export function CreateUserEducationRelationInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserEducationRelationInputDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'create': ((json['create'] as Array<any>).map(CreateEducationDtoFromJSON)),
    };
}

export function CreateUserEducationRelationInputDtoToJSON(value?: CreateUserEducationRelationInputDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create': ((value.create as Array<any>).map(CreateEducationDtoToJSON)),
    };
}

