/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateWorkDto,
    CreateWorkDtoFromJSON,
    CreateWorkDtoFromJSONTyped,
    CreateWorkDtoToJSON,
} from './CreateWorkDto';

/**
 * 
 * @export
 * @interface CreateUserWorkRelationInputDto
 */
export interface CreateUserWorkRelationInputDto {
    /**
     * 
     * @type {Array<CreateWorkDto>}
     * @memberof CreateUserWorkRelationInputDto
     */
    create: Array<CreateWorkDto>;
}

export function CreateUserWorkRelationInputDtoFromJSON(json: any): CreateUserWorkRelationInputDto {
    return CreateUserWorkRelationInputDtoFromJSONTyped(json, false);
}

export function CreateUserWorkRelationInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserWorkRelationInputDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'create': ((json['create'] as Array<any>).map(CreateWorkDtoFromJSON)),
    };
}

export function CreateUserWorkRelationInputDtoToJSON(value?: CreateUserWorkRelationInputDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'create': ((value.create as Array<any>).map(CreateWorkDtoToJSON)),
    };
}

