/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    DatamodelEnum,
    DatamodelEnumFromJSON,
    DatamodelEnumFromJSONTyped,
    DatamodelEnumToJSON,
} from './DatamodelEnum';
import {
    Model,
    ModelFromJSON,
    ModelFromJSONTyped,
    ModelToJSON,
} from './Model';

/**
 * 
 * @export
 * @interface Datamodel
 */
export interface Datamodel {
    /**
     * 
     * @type {Array<Model>}
     * @memberof Datamodel
     */
    models: Array<Model>;
    /**
     * 
     * @type {Array<DatamodelEnum>}
     * @memberof Datamodel
     */
    enums: Array<DatamodelEnum>;
}

export function DatamodelFromJSON(json: any): Datamodel {
    return DatamodelFromJSONTyped(json, false);
}

export function DatamodelFromJSONTyped(json: any, ignoreDiscriminator: boolean): Datamodel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'models': ((json['models'] as Array<any>).map(ModelFromJSON)),
        'enums': ((json['enums'] as Array<any>).map(DatamodelEnumFromJSON)),
    };
}

export function DatamodelToJSON(value?: Datamodel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'models': ((value.models as Array<any>).map(ModelToJSON)),
        'enums': ((value.enums as Array<any>).map(DatamodelEnumToJSON)),
    };
}

