/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EducationUpdateDto
 */
export interface EducationUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof EducationUpdateDto
     */
    institution?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdateDto
     */
    area?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdateDto
     */
    studyType?: string;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdateDto
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof EducationUpdateDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EducationUpdateDto
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof EducationUpdateDto
     */
    score?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EducationUpdateDto
     */
    courses?: Array<string>;
}

export function EducationUpdateDtoFromJSON(json: any): EducationUpdateDto {
    return EducationUpdateDtoFromJSONTyped(json, false);
}

export function EducationUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'institution': !exists(json, 'institution') ? undefined : json['institution'],
        'area': !exists(json, 'area') ? undefined : json['area'],
        'studyType': !exists(json, 'studyType') ? undefined : json['studyType'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'score': !exists(json, 'score') ? undefined : json['score'],
        'courses': !exists(json, 'courses') ? undefined : json['courses'],
    };
}

export function EducationUpdateDtoToJSON(value?: EducationUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'institution': value.institution,
        'area': value.area,
        'studyType': value.studyType,
        'url': value.url,
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'score': value.score,
        'courses': value.courses,
    };
}

