/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface EducationEntity
 */
export interface EducationEntity {
    /**
     * 
     * @type {number}
     * @memberof EducationEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EducationEntity
     */
    institution: string;
    /**
     * 
     * @type {string}
     * @memberof EducationEntity
     */
    area: string;
    /**
     * 
     * @type {string}
     * @memberof EducationEntity
     */
    studyType: string;
    /**
     * 
     * @type {string}
     * @memberof EducationEntity
     */
    url: string;
    /**
     * 
     * @type {Date}
     * @memberof EducationEntity
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof EducationEntity
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof EducationEntity
     */
    score: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EducationEntity
     */
    courses: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof EducationEntity
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof EducationEntity
     */
    user?: User | null;
}

export function EducationEntityFromJSON(json: any): EducationEntity {
    return EducationEntityFromJSONTyped(json, false);
}

export function EducationEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): EducationEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'institution': json['institution'],
        'area': json['area'],
        'studyType': json['studyType'],
        'url': json['url'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'score': json['score'],
        'courses': json['courses'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function EducationEntityToJSON(value?: EducationEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'institution': value.institution,
        'area': value.area,
        'studyType': value.studyType,
        'url': value.url,
        'startDate': (value.startDate.toISOString()),
        'endDate': (value.endDate.toISOString()),
        'score': value.score,
        'courses': value.courses,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

