/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterestsUpdateDto
 */
export interface InterestsUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof InterestsUpdateDto
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InterestsUpdateDto
     */
    keywords?: Array<string>;
}

export function InterestsUpdateDtoFromJSON(json: any): InterestsUpdateDto {
    return InterestsUpdateDtoFromJSONTyped(json, false);
}

export function InterestsUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestsUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
    };
}

export function InterestsUpdateDtoToJSON(value?: InterestsUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'keywords': value.keywords,
    };
}

