/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InterestUpdateDto
 */
export interface InterestUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof InterestUpdateDto
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InterestUpdateDto
     */
    keywords?: Array<string>;
}

export function InterestUpdateDtoFromJSON(json: any): InterestUpdateDto {
    return InterestUpdateDtoFromJSONTyped(json, false);
}

export function InterestUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InterestUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
    };
}

export function InterestUpdateDtoToJSON(value?: InterestUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'keywords': value.keywords,
    };
}

