/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateLanguageUserRelationInputDto,
    CreateLanguageUserRelationInputDtoFromJSON,
    CreateLanguageUserRelationInputDtoFromJSONTyped,
    CreateLanguageUserRelationInputDtoToJSON,
} from './CreateLanguageUserRelationInputDto';

/**
 * 
 * @export
 * @interface LanguagesCreateDto
 */
export interface LanguagesCreateDto {
    /**
     * 
     * @type {string}
     * @memberof LanguagesCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof LanguagesCreateDto
     */
    fluency: string;
    /**
     * 
     * @type {CreateLanguageUserRelationInputDto}
     * @memberof LanguagesCreateDto
     */
    user?: CreateLanguageUserRelationInputDto;
}

export function LanguagesCreateDtoFromJSON(json: any): LanguagesCreateDto {
    return LanguagesCreateDtoFromJSONTyped(json, false);
}

export function LanguagesCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LanguagesCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'fluency': json['fluency'],
        'user': !exists(json, 'user') ? undefined : CreateLanguageUserRelationInputDtoFromJSON(json['user']),
    };
}

export function LanguagesCreateDtoToJSON(value?: LanguagesCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'fluency': value.fluency,
        'user': CreateLanguageUserRelationInputDtoToJSON(value.user),
    };
}

