/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateLocationUserRelationInputDto,
    CreateLocationUserRelationInputDtoFromJSON,
    CreateLocationUserRelationInputDtoFromJSONTyped,
    CreateLocationUserRelationInputDtoToJSON,
} from './CreateLocationUserRelationInputDto';

/**
 * 
 * @export
 * @interface LocationsCreateDto
 */
export interface LocationsCreateDto {
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateDto
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateDto
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateDto
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateDto
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof LocationsCreateDto
     */
    region: string;
    /**
     * 
     * @type {CreateLocationUserRelationInputDto}
     * @memberof LocationsCreateDto
     */
    user?: CreateLocationUserRelationInputDto;
}

export function LocationsCreateDtoFromJSON(json: any): LocationsCreateDto {
    return LocationsCreateDtoFromJSONTyped(json, false);
}

export function LocationsCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LocationsCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'address': json['address'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'countryCode': json['countryCode'],
        'region': json['region'],
        'user': !exists(json, 'user') ? undefined : CreateLocationUserRelationInputDtoFromJSON(json['user']),
    };
}

export function LocationsCreateDtoToJSON(value?: LocationsCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'address': value.address,
        'postalCode': value.postalCode,
        'city': value.city,
        'countryCode': value.countryCode,
        'region': value.region,
        'user': CreateLocationUserRelationInputDtoToJSON(value.user),
    };
}

