/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    address: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    countryCode: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    region: string;
    /**
     * 
     * @type {number}
     * @memberof Location
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof Location
     */
    user?: User | null;
}

export function LocationFromJSON(json: any): Location {
    return LocationFromJSONTyped(json, false);
}

export function LocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Location {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'address': json['address'],
        'postalCode': json['postalCode'],
        'city': json['city'],
        'countryCode': json['countryCode'],
        'region': json['region'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function LocationToJSON(value?: Location | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'address': value.address,
        'postalCode': value.postalCode,
        'city': value.city,
        'countryCode': value.countryCode,
        'region': value.region,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

