/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrimaryKey
 */
export interface PrimaryKey {
    /**
     * 
     * @type {string}
     * @memberof PrimaryKey
     */
    name: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof PrimaryKey
     */
    fields: Array<string>;
}

export function PrimaryKeyFromJSON(json: any): PrimaryKey {
    return PrimaryKeyFromJSONTyped(json, false);
}

export function PrimaryKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrimaryKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'fields': json['fields'],
    };
}

export function PrimaryKeyToJSON(value?: PrimaryKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'fields': value.fields,
    };
}

