/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfilesUpdateDto
 */
export interface ProfilesUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ProfilesUpdateDto
     */
    network?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfilesUpdateDto
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof ProfilesUpdateDto
     */
    url?: string;
}

export function ProfilesUpdateDtoFromJSON(json: any): ProfilesUpdateDto {
    return ProfilesUpdateDtoFromJSONTyped(json, false);
}

export function ProfilesUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': !exists(json, 'network') ? undefined : json['network'],
        'username': !exists(json, 'username') ? undefined : json['username'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function ProfilesUpdateDtoToJSON(value?: ProfilesUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'username': value.username,
        'url': value.url,
    };
}

