/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ProfileEntity
 */
export interface ProfileEntity {
    /**
     * 
     * @type {number}
     * @memberof ProfileEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileEntity
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileEntity
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ProfileEntity
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof ProfileEntity
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof ProfileEntity
     */
    user?: User | null;
}

export function ProfileEntityFromJSON(json: any): ProfileEntity {
    return ProfileEntityFromJSONTyped(json, false);
}

export function ProfileEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'network': json['network'],
        'username': json['username'],
        'url': json['url'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function ProfileEntityToJSON(value?: ProfileEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'network': value.network,
        'username': value.username,
        'url': value.url,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

