/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateProfileUserRelationInputDto,
    CreateProfileUserRelationInputDtoFromJSON,
    CreateProfileUserRelationInputDtoFromJSONTyped,
    CreateProfileUserRelationInputDtoToJSON,
} from './CreateProfileUserRelationInputDto';

/**
 * 
 * @export
 * @interface ProfilesCreateDto
 */
export interface ProfilesCreateDto {
    /**
     * 
     * @type {string}
     * @memberof ProfilesCreateDto
     */
    network: string;
    /**
     * 
     * @type {string}
     * @memberof ProfilesCreateDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof ProfilesCreateDto
     */
    url: string;
    /**
     * 
     * @type {CreateProfileUserRelationInputDto}
     * @memberof ProfilesCreateDto
     */
    user?: CreateProfileUserRelationInputDto;
}

export function ProfilesCreateDtoFromJSON(json: any): ProfilesCreateDto {
    return ProfilesCreateDtoFromJSONTyped(json, false);
}

export function ProfilesCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfilesCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'network': json['network'],
        'username': json['username'],
        'url': json['url'],
        'user': !exists(json, 'user') ? undefined : CreateProfileUserRelationInputDtoFromJSON(json['user']),
    };
}

export function ProfilesCreateDtoToJSON(value?: ProfilesCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network': value.network,
        'username': value.username,
        'url': value.url,
        'user': CreateProfileUserRelationInputDtoToJSON(value.user),
    };
}

