/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Project
     */
    highlights: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Project
     */
    keywords: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Project
     */
    roles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    entity: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof Project
     */
    user?: User | null;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'description': json['description'],
        'highlights': json['highlights'],
        'keywords': json['keywords'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'url': json['url'],
        'roles': json['roles'],
        'entity': json['entity'],
        'type': json['type'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function ProjectToJSON(value?: Project | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'highlights': value.highlights,
        'keywords': value.keywords,
        'startDate': (value.startDate.toISOString()),
        'endDate': (value.endDate.toISOString()),
        'url': value.url,
        'roles': value.roles,
        'entity': value.entity,
        'type': value.type,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

