/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateProjectUserRelationInputDto,
    CreateProjectUserRelationInputDtoFromJSON,
    CreateProjectUserRelationInputDtoFromJSONTyped,
    CreateProjectUserRelationInputDtoToJSON,
} from './CreateProjectUserRelationInputDto';

/**
 * 
 * @export
 * @interface ProjectCreateDto
 */
export interface ProjectCreateDto {
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    description: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateDto
     */
    highlights: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateDto
     */
    keywords: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ProjectCreateDto
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectCreateDto
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectCreateDto
     */
    roles: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    entity: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectCreateDto
     */
    type: string;
    /**
     * 
     * @type {CreateProjectUserRelationInputDto}
     * @memberof ProjectCreateDto
     */
    user?: CreateProjectUserRelationInputDto;
}

export function ProjectCreateDtoFromJSON(json: any): ProjectCreateDto {
    return ProjectCreateDtoFromJSONTyped(json, false);
}

export function ProjectCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'highlights': json['highlights'],
        'keywords': json['keywords'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'url': json['url'],
        'roles': json['roles'],
        'entity': json['entity'],
        'type': json['type'],
        'user': !exists(json, 'user') ? undefined : CreateProjectUserRelationInputDtoFromJSON(json['user']),
    };
}

export function ProjectCreateDtoToJSON(value?: ProjectCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'highlights': value.highlights,
        'keywords': value.keywords,
        'startDate': (value.startDate.toISOString()),
        'endDate': (value.endDate.toISOString()),
        'url': value.url,
        'roles': value.roles,
        'entity': value.entity,
        'type': value.type,
        'user': CreateProjectUserRelationInputDtoToJSON(value.user),
    };
}

