/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUpdateDto
 */
export interface ProjectUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDto
     */
    description?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectUpdateDto
     */
    highlights?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectUpdateDto
     */
    keywords?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ProjectUpdateDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProjectUpdateDto
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDto
     */
    url?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ProjectUpdateDto
     */
    roles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDto
     */
    entity?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUpdateDto
     */
    type?: string;
}

export function ProjectUpdateDtoFromJSON(json: any): ProjectUpdateDto {
    return ProjectUpdateDtoFromJSONTyped(json, false);
}

export function ProjectUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'highlights': !exists(json, 'highlights') ? undefined : json['highlights'],
        'keywords': !exists(json, 'keywords') ? undefined : json['keywords'],
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'url': !exists(json, 'url') ? undefined : json['url'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
        'entity': !exists(json, 'entity') ? undefined : json['entity'],
        'type': !exists(json, 'type') ? undefined : json['type'],
    };
}

export function ProjectUpdateDtoToJSON(value?: ProjectUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'highlights': value.highlights,
        'keywords': value.keywords,
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'url': value.url,
        'roles': value.roles,
        'entity': value.entity,
        'type': value.type,
    };
}

