/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicationsUpdateDto
 */
export interface PublicationsUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof PublicationsUpdateDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationsUpdateDto
     */
    publisher?: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationsUpdateDto
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicationsUpdateDto
     */
    releaseDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicationsUpdateDto
     */
    summary?: string;
}

export function PublicationsUpdateDtoFromJSON(json: any): PublicationsUpdateDto {
    return PublicationsUpdateDtoFromJSONTyped(json, false);
}

export function PublicationsUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicationsUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'publisher': !exists(json, 'publisher') ? undefined : json['publisher'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'releaseDate': !exists(json, 'releaseDate') ? undefined : (new Date(json['releaseDate'])),
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
    };
}

export function PublicationsUpdateDtoToJSON(value?: PublicationsUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'publisher': value.publisher,
        'url': value.url,
        'releaseDate': value.releaseDate === undefined ? undefined : (value.releaseDate.toISOString()),
        'summary': value.summary,
    };
}

