/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface PublicationEntity
 */
export interface PublicationEntity {
    /**
     * 
     * @type {number}
     * @memberof PublicationEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PublicationEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationEntity
     */
    publisher: string;
    /**
     * 
     * @type {string}
     * @memberof PublicationEntity
     */
    url: string;
    /**
     * 
     * @type {Date}
     * @memberof PublicationEntity
     */
    releaseDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PublicationEntity
     */
    summary: string;
    /**
     * 
     * @type {number}
     * @memberof PublicationEntity
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof PublicationEntity
     */
    user?: User | null;
}

export function PublicationEntityFromJSON(json: any): PublicationEntity {
    return PublicationEntityFromJSONTyped(json, false);
}

export function PublicationEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicationEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'publisher': json['publisher'],
        'url': json['url'],
        'releaseDate': (new Date(json['releaseDate'])),
        'summary': json['summary'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function PublicationEntityToJSON(value?: PublicationEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'publisher': value.publisher,
        'url': value.url,
        'releaseDate': (value.releaseDate.toISOString()),
        'summary': value.summary,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

