/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateReferenceUserRelationInputDto,
    CreateReferenceUserRelationInputDtoFromJSON,
    CreateReferenceUserRelationInputDtoFromJSONTyped,
    CreateReferenceUserRelationInputDtoToJSON,
} from './CreateReferenceUserRelationInputDto';

/**
 * 
 * @export
 * @interface ReferencesCreateDto
 */
export interface ReferencesCreateDto {
    /**
     * 
     * @type {string}
     * @memberof ReferencesCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReferencesCreateDto
     */
    reference: string;
    /**
     * 
     * @type {CreateReferenceUserRelationInputDto}
     * @memberof ReferencesCreateDto
     */
    user?: CreateReferenceUserRelationInputDto;
}

export function ReferencesCreateDtoFromJSON(json: any): ReferencesCreateDto {
    return ReferencesCreateDtoFromJSONTyped(json, false);
}

export function ReferencesCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferencesCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'reference': json['reference'],
        'user': !exists(json, 'user') ? undefined : CreateReferenceUserRelationInputDtoFromJSON(json['user']),
    };
}

export function ReferencesCreateDtoToJSON(value?: ReferencesCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'reference': value.reference,
        'user': CreateReferenceUserRelationInputDtoToJSON(value.user),
    };
}

