/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ReferenceEntity
 */
export interface ReferenceEntity {
    /**
     * 
     * @type {number}
     * @memberof ReferenceEntity
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ReferenceEntity
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReferenceEntity
     */
    reference: string;
    /**
     * 
     * @type {number}
     * @memberof ReferenceEntity
     */
    userId: number | null;
    /**
     * 
     * @type {User}
     * @memberof ReferenceEntity
     */
    user?: User | null;
}

export function ReferenceEntityFromJSON(json: any): ReferenceEntity {
    return ReferenceEntityFromJSONTyped(json, false);
}

export function ReferenceEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReferenceEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'reference': json['reference'],
        'userId': json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
    };
}

export function ReferenceEntityToJSON(value?: ReferenceEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'reference': value.reference,
        'userId': value.userId,
        'user': UserToJSON(value.user),
    };
}

