/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SchemaEnum,
    SchemaEnumFromJSON,
    SchemaEnumFromJSONTyped,
    SchemaEnumToJSON,
} from './SchemaEnum';

/**
 * 
 * @export
 * @interface SchemaEnumTypes
 */
export interface SchemaEnumTypes {
    /**
     * 
     * @type {Array<SchemaEnum>}
     * @memberof SchemaEnumTypes
     */
    model?: Array<SchemaEnum>;
    /**
     * 
     * @type {Array<SchemaEnum>}
     * @memberof SchemaEnumTypes
     */
    prisma: Array<SchemaEnum>;
}

export function SchemaEnumTypesFromJSON(json: any): SchemaEnumTypes {
    return SchemaEnumTypesFromJSONTyped(json, false);
}

export function SchemaEnumTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaEnumTypes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model': !exists(json, 'model') ? undefined : ((json['model'] as Array<any>).map(SchemaEnumFromJSON)),
        'prisma': ((json['prisma'] as Array<any>).map(SchemaEnumFromJSON)),
    };
}

export function SchemaEnumTypesToJSON(value?: SchemaEnumTypes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model': value.model === undefined ? undefined : ((value.model as Array<any>).map(SchemaEnumToJSON)),
        'prisma': ((value.prisma as Array<any>).map(SchemaEnumToJSON)),
    };
}

