/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OutputType,
    OutputTypeFromJSON,
    OutputTypeFromJSONTyped,
    OutputTypeToJSON,
} from './OutputType';

/**
 * 
 * @export
 * @interface SchemaOutputObjectTypes
 */
export interface SchemaOutputObjectTypes {
    /**
     * 
     * @type {Array<OutputType>}
     * @memberof SchemaOutputObjectTypes
     */
    model: Array<OutputType>;
    /**
     * 
     * @type {Array<OutputType>}
     * @memberof SchemaOutputObjectTypes
     */
    prisma: Array<OutputType>;
}

export function SchemaOutputObjectTypesFromJSON(json: any): SchemaOutputObjectTypes {
    return SchemaOutputObjectTypesFromJSONTyped(json, false);
}

export function SchemaOutputObjectTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaOutputObjectTypes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model': ((json['model'] as Array<any>).map(OutputTypeFromJSON)),
        'prisma': ((json['prisma'] as Array<any>).map(OutputTypeFromJSON)),
    };
}

export function SchemaOutputObjectTypesToJSON(value?: SchemaOutputObjectTypes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model': ((value.model as Array<any>).map(OutputTypeToJSON)),
        'prisma': ((value.prisma as Array<any>).map(OutputTypeToJSON)),
    };
}

