/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Skill,
    SkillFromJSON,
    SkillFromJSONTyped,
    SkillToJSON,
} from './Skill';

/**
 * 
 * @export
 * @interface SkillKeywordEntity
 */
export interface SkillKeywordEntity {
    /**
     * 
     * @type {number}
     * @memberof SkillKeywordEntity
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof SkillKeywordEntity
     */
    skillId: number | null;
    /**
     * 
     * @type {Skill}
     * @memberof SkillKeywordEntity
     */
    skill?: Skill | null;
}

export function SkillKeywordEntityFromJSON(json: any): SkillKeywordEntity {
    return SkillKeywordEntityFromJSONTyped(json, false);
}

export function SkillKeywordEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillKeywordEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'skillId': json['skillId'],
        'skill': !exists(json, 'skill') ? undefined : SkillFromJSON(json['skill']),
    };
}

export function SkillKeywordEntityToJSON(value?: SkillKeywordEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'skillId': value.skillId,
        'skill': SkillToJSON(value.skill),
    };
}

