/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateSkillKeywordSkillRelationInputDto,
    CreateSkillKeywordSkillRelationInputDtoFromJSON,
    CreateSkillKeywordSkillRelationInputDtoFromJSONTyped,
    CreateSkillKeywordSkillRelationInputDtoToJSON,
} from './CreateSkillKeywordSkillRelationInputDto';

/**
 * 
 * @export
 * @interface SkillKeywordCreateDto
 */
export interface SkillKeywordCreateDto {
    /**
     * 
     * @type {CreateSkillKeywordSkillRelationInputDto}
     * @memberof SkillKeywordCreateDto
     */
    skill?: CreateSkillKeywordSkillRelationInputDto;
}

export function SkillKeywordCreateDtoFromJSON(json: any): SkillKeywordCreateDto {
    return SkillKeywordCreateDtoFromJSONTyped(json, false);
}

export function SkillKeywordCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillKeywordCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'skill': !exists(json, 'skill') ? undefined : CreateSkillKeywordSkillRelationInputDtoFromJSON(json['skill']),
    };
}

export function SkillKeywordCreateDtoToJSON(value?: SkillKeywordCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'skill': CreateSkillKeywordSkillRelationInputDtoToJSON(value.skill),
    };
}

