/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateSkillKeywordsRelationInputDto,
    CreateSkillKeywordsRelationInputDtoFromJSON,
    CreateSkillKeywordsRelationInputDtoFromJSONTyped,
    CreateSkillKeywordsRelationInputDtoToJSON,
} from './CreateSkillKeywordsRelationInputDto';
import {
    CreateSkillUserRelationInputDto,
    CreateSkillUserRelationInputDtoFromJSON,
    CreateSkillUserRelationInputDtoFromJSONTyped,
    CreateSkillUserRelationInputDtoToJSON,
} from './CreateSkillUserRelationInputDto';

/**
 * 
 * @export
 * @interface SkillCreateDto
 */
export interface SkillCreateDto {
    /**
     * 
     * @type {string}
     * @memberof SkillCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SkillCreateDto
     */
    level: string;
    /**
     * 
     * @type {CreateSkillKeywordsRelationInputDto}
     * @memberof SkillCreateDto
     */
    keywords?: CreateSkillKeywordsRelationInputDto;
    /**
     * 
     * @type {CreateSkillUserRelationInputDto}
     * @memberof SkillCreateDto
     */
    user?: CreateSkillUserRelationInputDto;
}

export function SkillCreateDtoFromJSON(json: any): SkillCreateDto {
    return SkillCreateDtoFromJSONTyped(json, false);
}

export function SkillCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkillCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'level': json['level'],
        'keywords': !exists(json, 'keywords') ? undefined : CreateSkillKeywordsRelationInputDtoFromJSON(json['keywords']),
        'user': !exists(json, 'user') ? undefined : CreateSkillUserRelationInputDtoFromJSON(json['user']),
    };
}

export function SkillCreateDtoToJSON(value?: SkillCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'level': value.level,
        'keywords': CreateSkillKeywordsRelationInputDtoToJSON(value.keywords),
        'user': CreateSkillUserRelationInputDtoToJSON(value.user),
    };
}

