/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkUpdateDto
 */
export interface WorkUpdateDto {
    /**
     * 
     * @type {string}
     * @memberof WorkUpdateDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkUpdateDto
     */
    position?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkUpdateDto
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkUpdateDto
     */
    url?: string;
    /**
     * 
     * @type {Date}
     * @memberof WorkUpdateDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkUpdateDto
     */
    endDate?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorkUpdateDto
     */
    highlights?: Array<string>;
}

export function WorkUpdateDtoFromJSON(json: any): WorkUpdateDto {
    return WorkUpdateDtoFromJSONTyped(json, false);
}

export function WorkUpdateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkUpdateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'position': !exists(json, 'position') ? undefined : json['position'],
        'summary': !exists(json, 'summary') ? undefined : json['summary'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'highlights': !exists(json, 'highlights') ? undefined : json['highlights'],
    };
}

export function WorkUpdateDtoToJSON(value?: WorkUpdateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'position': value.position,
        'summary': value.summary,
        'url': value.url,
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'highlights': value.highlights,
    };
}

