/* tslint:disable */
/* eslint-disable */
/**
 * JSON Resume
 * Standarized resumes
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CreateWorkUserRelationInputDto,
    CreateWorkUserRelationInputDtoFromJSON,
    CreateWorkUserRelationInputDtoFromJSONTyped,
    CreateWorkUserRelationInputDtoToJSON,
} from './CreateWorkUserRelationInputDto';

/**
 * 
 * @export
 * @interface WorksCreateDto
 */
export interface WorksCreateDto {
    /**
     * 
     * @type {string}
     * @memberof WorksCreateDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof WorksCreateDto
     */
    position: string;
    /**
     * 
     * @type {string}
     * @memberof WorksCreateDto
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof WorksCreateDto
     */
    url: string;
    /**
     * 
     * @type {Date}
     * @memberof WorksCreateDto
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorksCreateDto
     */
    endDate: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof WorksCreateDto
     */
    highlights: Array<string>;
    /**
     * 
     * @type {CreateWorkUserRelationInputDto}
     * @memberof WorksCreateDto
     */
    user?: CreateWorkUserRelationInputDto;
}

export function WorksCreateDtoFromJSON(json: any): WorksCreateDto {
    return WorksCreateDtoFromJSONTyped(json, false);
}

export function WorksCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorksCreateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'position': json['position'],
        'summary': json['summary'],
        'url': json['url'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'highlights': json['highlights'],
        'user': !exists(json, 'user') ? undefined : CreateWorkUserRelationInputDtoFromJSON(json['user']),
    };
}

export function WorksCreateDtoToJSON(value?: WorksCreateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'position': value.position,
        'summary': value.summary,
        'url': value.url,
        'startDate': (value.startDate.toISOString()),
        'endDate': (value.endDate.toISOString()),
        'highlights': value.highlights,
        'user': CreateWorkUserRelationInputDtoToJSON(value.user),
    };
}

